name: Rename Images Sequentially

on:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Rename .jpg files in /images
        run: |
          # Navigate to the images folder
          cd images
          
          # Initialize counter for renaming
          i=1
          
          # Loop through all jpg files and rename them sequentially
          for file in *.jpg; do
            new_name="${i}.jpg"
            # Only rename if the file name is different
            if [ "$file" != "$new_name" ]; then
              mv "$file" "$new_name"
            fi
            i=$((i + 1))  # Increment counter
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add images/
          git commit -m "Renamed images to sequential numbers"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/OnemanCircle/Slider.git HEAD:main
